### ISSUE TITLE
Bengali Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-bn#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Keep track your translation progression

https://isgatsbytranslatedyet.org/

## Discord Channel for communication

Go to discord: https://discord.gg/684x8vK
Feel free to ask any questions in the #translation-bn channel

# Work List

 - 🏃 Work in Progress
-  👀 In Review

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@ayan-b) #2
    

### Tutorial

* [x] tutorial/index (@nutboltu) #4 
* [ ] tutorial/part-zero (@mkhan037)
* [ ] tutorial/part-one
* [ ] 🏃 tutorial/part-two (@JubayerJoy)
* [ ] tutorial/part-three
* [ ] tutorial/part-four
* [ ] 🏃 tutorial/part-five (@prateekpardeshi)
* [x] tutorial/part-six (@JubayerJoy)
* [ ] tutorial/part-seven
* [ ] tutorial/part-eight
    

### Docs

* [x]  docs/index (@mkhan037) #5 
* [x] docs/quick-start (@shakib609) #3 
* [ ] docs/glossary (@khodarkhashi)
* [x] docs/gatsby-cli (@ayan-b) #6
    
#### Recipes

* [ ] docs/recipes
* [ ] docs/recipes/pages-layouts
* [ ] docs/recipes/styling-css
* [ ] docs/recipes/working-with-starters
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site

#### API Reference

* [x] docs/api-reference (@ayan-b) #15
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image (@shaonkabir8)
* [ ] docs/gatsby-config
* [x] docs/browser-apis (@ayan-b) #19
* [x]  docs/ssr-apis (@shakib609) #18
* [x] docs/api-files (@Twaha-Rahman)
* [ ] docs/api-files-gatsby-config
* [x] docs/api-files-gatsby-browser (@shakib609) #22
* [ ] 🏃docs/api-files-gatsby-node (@Twaha-Rahman)
* [x] docs/api-files-gatsby-ssr (@shakib609) #23
* [x] docs/actions (@shakib609) #17
* [ ] docs/graphql-api (@shaonkabir8)
* [x] docs/node-apis (@krahul32)
* [ ] docs/node-api-helpers
* [x] docs/node-model (@ayan-b) #16
* [ ] docs/node-interface (@GeekBoySupreme)
* [ ] docs/schema-customization
* [ ] docs/api-specification (@GeekBoySupreme)

**Comment by shakib609** [comment]
docs/quick-start

**Comment by ayan-b** [comment]
I would like to translate [community/code-of-conduct](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/contributing/code-of-conduct.md).

**Comment by mkhan037** [comment]
I would like to translate docs/index

**Comment by ayan-b** [comment]
I would like to translate [docs/gatsby-cli](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/docs/gatsby-cli.md).

**Comment by mkhan037** [comment]
I would like to translate tutorial/part-zero

**Comment by the-coder-dude** [comment]
@nutboltu Can I take `docs/contributing/how-to-contribute.md` ? 🙂

**Comment by shakib609** [comment]
Yeah, sure. Assigning it to you.

**Comment by shakib609** [comment]
@prateekpardeshi Please choose one of the available pages in the first comment. We'd like to translate these core pages first so that we can officially release the bengali translation. Otherwise, the translations will not be considered as an official Gatsby localization.

**Comment by the-coder-dude** [comment]
@shakib609 I understand. I want to take `tutorial/part-five` 🙂

**Comment by shakib609** [comment]
Thanks @prateekpardeshi. Assigned the translation to you.

**Comment by mdafibuzzaman** [comment]
Can I take docs/glossary/node.md ? :)

**Comment by mdafibuzzaman** [comment]
I would like to translate docs/glossary/react.md. :)

**Comment by nutboltu** [comment]
@khodarkhashi assigned you to docs/glossary.

**Comment by spielers** [comment]
I want to translate add-404-page.md

**Comment by spielers** [comment]
translated  please review

**Comment by nutboltu** [comment]
@spielers , thanks for translating this page. we highly recommend translating the core pages mentioned in the issues.
But we'll sure review your PR and hopefully going to merge soon!

**Comment by ayan-b** [comment]
I would like to translate [docs/api-reference](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/docs/api-reference.md).

**Comment by ayan-b** [comment]
I would like to translate [docs/node-model](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/docs/node-model.md).

**Comment by ayan-b** [comment]
I would like to translate [docs/browser-apis](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/docs/browser-apis.md).

**Comment by Twaha-Rahman** [comment]
I didn't know that Gatsby docs were getting translated😅! I'd like to contribute to this project and help translate the Gatsby docs. 

@nutboltu Can you please assign me the `docs/api-files` and `docs/api-files-gatsby-node` pages? (I'm taking two pages cause they are quite small and would be the size of a single page when combined😉)

**Comment by shakib609** [comment]
Assigned to you @Twaha-Rahman.

**Comment by Twaha-Rahman** [comment]
Thanks @shakib609 !

**Comment by krahul32** [comment]
Hi! I'll be taking `docs/node-apis` .
`

**Comment by shakib609** [comment]
Assigned to you @krahul32

**Comment by krahul32** [comment]
> Assigned to you @krahul32

I translate it.

**Comment by JubayerJoy** [comment]
Hi @nutboltu, @shakib609 I want to take `tutorial/part-six` 🙂

**Comment by shakib609** [comment]
Assigned to you @JubayerJoy

**Comment by JubayerJoy** [comment]
Hi @shakib609 , @nutboltu  I am done with `tutorial/part-six` and want to work on `tutorial/part-two`.  😃

**Comment by shakib609** [comment]
Great! :rocket: Assigned to you. @JubayerJoy
Will review your PRs soon.

**Comment by shaonkabir8** [comment]
Hi :wave:
I'd like to be assigned to translate the following pages :pray: 
-  [docs/gatsby-image](https://github.com/gatsbyjs/gatsby-bn/tree/master/docs/docs)
-  [docs/graphql-api](https://github.com/gatsbyjs/gatsby-bn/blob/master/docs/docs/graphql-api.md)


It gonna be amazing :rocket: 
Thanks.

**Comment by nutboltu** [comment]
@shaonkabir8 assigned those pages to you!

**Comment by GeekBoySupreme** [comment]
Hey, I found - `docs/api-specification` still needs to be translated.
Would love to have that assigned to me @nutboltu @shakib609

**Comment by shakib609** [comment]
> Hey, I found - `docs/api-specification` still needs to be translated.
> Would love to have that assigned to me @nutboltu @shakib609

Assigned :v:

**Comment by GeekBoySupreme** [comment]
@nutboltu @shakib609 I have some time this weekend. Could you assign me - `docs/node-interface` ?

**Comment by shakib609** [comment]
> @nutboltu @shakib609 I have some time this weekend. Could you assign me - `docs/node-interface` ?

Assigned @GeekBoySupreme

**Comment by GeekBoySupreme** [comment]
Hey @shakib609 @nutboltu it's been a while. 
I would want to pick up `docs/recipes/transforming-data` this weekend

**Comment by shakib609** [comment]
Hi @GeekBoySupreme 
I see that you are already assigned to two pages Are you working on those?
Shall I unassign those from you and assign you to the new page?

**Comment by GeekBoySupreme** [comment]
@shakib609 those have been done and merged too. 
The issue list needs an update too

**Comment by heysagnik** [comment]
Please approve my pull request @shakib609

**Comment by GeekBoySupreme** [comment]
@shakib609 soft reminder.
For the previous pages assigned to me - check PR #35 and #33
